Topic 5: NumPy


In [1]:
import numpy as np
import time

np.random.seed(42)

# ── 1. Array creation patterns ───────────────────────────────
print("=== ARRAY CREATION ===")
print(f"zeros:   {np.zeros((2,3))}")
print(f"eye:\n{np.eye(3)}")
print(f"linspace: {np.linspace(0, 1, 5)}")
print(f"randn shape: {np.random.randn(3, 4).shape}")

# ── 2. Indexing & Slicing ─────────────────────────────────────
print("\n=== INDEXING ===")
X = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
    [11, 22, 33],
])

print(f"First row:       {X[0]}")
print(f"Last row:        {X[-1]}")
print(f"Column 1:        {X[:, 1]}")
print(f"Rows 1-2:      \n{X[1:3]}")
print(f"Values > 50:     {X[X > 50]}")

# Fancy indexing — select specific rows by index
rows = np.array([0, 2, 3])
print(f"Rows 0,2,3:\n{X[rows]}")

# ── 3. Broadcasting ───────────────────────────────────────────
print("\n=== BROADCASTING ===")
scores = np.array([
    [85, 90, 78],
    [70, 88, 95],
    [60, 72, 80],
    [95, 85, 88],
], dtype=float)

# Subtract column mean (normalize each feature)
col_means = scores.mean(axis=0)   # shape (3,)
print(f"Column means: {col_means}")

normalized = scores - col_means   # (4,3) - (3,) → broadcasts!
print(f"Normalized:\n{np.round(normalized, 2)}")
print(f"New column means: {np.round(normalized.mean(axis=0), 6)}")

# ── 4. Axis operations ────────────────────────────────────────
print("\n=== AXIS OPERATIONS ===")
print(f"scores.sum(axis=0): {scores.sum(axis=0)}")  # per feature total
print(f"scores.sum(axis=1): {scores.sum(axis=1)}")  # per student total
print(f"scores.mean(axis=0): {scores.mean(axis=0)}")
print(f"scores.max(axis=1):  {scores.max(axis=1)}")  # each student's best

# ── 5. Vectorization speed comparison ────────────────────────
print("\n=== VECTORIZATION SPEED ===")
data = np.random.randn(1_000_000)

# Python loop
start = time.time()
result_loop = [x**2 for x in data]
loop_time = time.time() - start

# NumPy vectorized
start = time.time()
result_np = data ** 2
np_time = time.time() - start

print(f"Python loop: {loop_time:.4f}s")
print(f"NumPy:       {np_time:.4f}s")
print(f"Speedup:     {loop_time/np_time:.1f}x faster")

# ── 6. Practical ML operations ───────────────────────────────
print("\n=== ML OPERATIONS ===")

# Softmax (converts raw scores to probabilities)
def softmax(x):
    e_x = np.exp(x - x.max())   # subtract max for numerical stability
    return e_x / e_x.sum()

logits = np.array([2.0, 1.0, 0.5])
probs = softmax(logits)
print(f"Logits: {logits}")
print(f"Softmax: {np.round(probs, 4)}  (sums to {probs.sum():.1f})")

# ReLU activation
def relu(x):
    return np.maximum(0, x)

activations = np.array([-2, -1, 0, 1, 3])
print(f"\nReLU({activations}) = {relu(activations)}")

# Z-score normalization (StandardScaler)
def standardize(X):
    return (X - X.mean(axis=0)) / X.std(axis=0)

X_std = standardize(scores)
print(f"\nStandardized scores mean: {np.round(X_std.mean(axis=0), 6)}")
print(f"Standardized scores std:  {np.round(X_std.std(axis=0), 4)}")

=== ARRAY CREATION ===
zeros:   [[0. 0. 0.]
 [0. 0. 0.]]
eye:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
linspace: [0.   0.25 0.5  0.75 1.  ]
randn shape: (3, 4)

=== INDEXING ===
First row:       [10 20 30]
Last row:        [11 22 33]
Column 1:        [20 50 80 22]
Rows 1-2:      
[[40 50 60]
 [70 80 90]]
Values > 50:     [60 70 80 90]
Rows 0,2,3:
[[10 20 30]
 [70 80 90]
 [11 22 33]]

=== BROADCASTING ===
Column means: [77.5  83.75 85.25]
Normalized:
[[  7.5    6.25  -7.25]
 [ -7.5    4.25   9.75]
 [-17.5  -11.75  -5.25]
 [ 17.5    1.25   2.75]]
New column means: [0. 0. 0.]

=== AXIS OPERATIONS ===
scores.sum(axis=0): [310. 335. 341.]
scores.sum(axis=1): [253. 253. 212. 268.]
scores.mean(axis=0): [77.5  83.75 85.25]
scores.max(axis=1):  [90. 95. 80. 95.]

=== VECTORIZATION SPEED ===
Python loop: 0.0734s
NumPy:       0.0013s
Speedup:     55.6x faster

=== ML OPERATIONS ===
Logits: [2.  1.  0.5]
Softmax: [0.6285 0.2312 0.1402]  (sums to 1.0)

ReLU([-2 -1  0  1  3]) = [0 0 0 1 3]

Standardized

In [41]:
import numpy as np
np.random.seed(42)

def relu(x):
    return np.maximum(0, x)

def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

X = np.random.randn(32, 8)

W1 = np.random.randn(8, 16) * 0.01
W2 = np.random.randn(16, 8) * 0.01
W3 = np.random.randn(8, 3) * 0.01

b1 = np.zeros(16)
b2 = np.zeros(8)
b3 = np.zeros(3)

Z1 = X @ W1 + b1
A1 = relu(Z1)
print(f"A1 : {A1.shape}")
Z2 = A1 @ W2 + b2
A2 = relu(Z2)
print(f"A2 : {A2.shape}")
Z3 = A2 @ W3 + b3
output = softmax(Z3)

print(f"output : {output.shape}")

print(f"rows sum should be 1(sample 5) : {output[:5].sum(axis = 1)}")

def predict(x):
    Z1 = X @ W1 + b1
    A1 = relu(Z1)

    Z2 = A1 @ W2 + b2
    A2 = relu(Z2)

    Z3 = A2 @ W3 + b3
    probs = softmax(Z3)

    return np.argmax(probs, axis= 1)

print(f"predicted : {predict(X)}")



A1 : (32, 16)
A2 : (32, 8)
output : (32, 3)
rows sum should be 1(sample 5) : [1. 1. 1. 1. 1.]
predicted : [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 2 1 0 0 0 1]
